Update to oci-sdk-go 13.1.0 for Qualsys issue
hashicorp/go-kms-wrapping pull request #42
Opened 2021-09-20 15:40 UTC by sgmiller

The Oracle OCI-go library was updated quite a while ago to add support for their London datacenter.  This branch was created to minimally upgrade the library to address a customer issue.  The library is now at 24.x, so we're pretty far behind.  However this addresses the issue for customers of Oracle's London DC.

2021-09-20 20:47 UTC, jefferai requested changes
Please `go mod tidy` when you update deps.

2021-09-20 20:48 UTC, jefferai commented
Any reason you're going from "super old" to "very old"? The current SDK version is `24.3.0`. I don't know the changes along the way but is there a reason not to just bump all the way up?

2021-09-30 21:17 UTC, sgmiller commented
No reason other than to address only this issue and not need to worry about any changes in the library that would break existing functionality.

2021-09-30 21:37 UTC, jefferai approved these changes

2021-09-30 21:37 UTC, merged